In [1]:
#importing needed packages
import torch 
import numpy as np

In [2]:
#1st part
np.random.seed(1)
a=np.random.randn(5,3)
b=np.random.randn(3,4)
print("first numpy array \"a\" with size {} is :-\n{}".format(a.shape,a))
print("second numpy array\"b\" with size {} is :-\n{}".format(b.shape,b))

first numpy array "a" with size (5, 3) is :-
[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]]
second numpy array"b" with size (3, 4) is :-
[[-1.09989127 -0.17242821 -0.87785842  0.04221375]
 [ 0.58281521 -1.10061918  1.14472371  0.90159072]
 [ 0.50249434  0.90085595 -0.68372786 -0.12289023]]


In [3]:
#2nd part
ta=torch.from_numpy(a)
tb=torch.from_numpy(b)
print("tensor of a:-\n{}".format(ta))
print("tensor of b:-\n{}".format(tb))

tensor of a:-
tensor([[ 1.6243, -0.6118, -0.5282],
        [-1.0730,  0.8654, -2.3015],
        [ 1.7448, -0.7612,  0.3190],
        [-0.2494,  1.4621, -2.0601],
        [-0.3224, -0.3841,  1.1338]], dtype=torch.float64)
tensor of b:-
tensor([[-1.0999, -0.1724, -0.8779,  0.0422],
        [ 0.5828, -1.1006,  1.1447,  0.9016],
        [ 0.5025,  0.9009, -0.6837, -0.1229]], dtype=torch.float64)


In [5]:
#3rd part
mul=torch.matmul(ta,tb)
print("Dot product of ta and tb(ta.tb)\n",mul)

Dot product of ta and tb(ta.tb)
 tensor([[-2.4085, -0.0826, -1.7651, -0.4181],
        [ 0.5280, -2.8408,  3.5062,  1.0178],
        [-2.2024,  0.8244, -2.6212, -0.6518],
        [ 0.0912, -3.4221,  3.3012,  1.5609],
        [ 0.7005,  1.4997, -0.9318, -0.4992]], dtype=torch.float64)
