In [0]:
import torch

In [3]:
x = torch.empty(3, 3)
print(x)

tensor([[6.5990e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 4.4842e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


In [4]:
x = torch.rand(3, 3)
print(x)

tensor([[0.3148, 0.5240, 0.0209],
        [0.4237, 0.8674, 0.4590],
        [0.1805, 0.5817, 0.0097]])


In [5]:
x = torch.zeros(3, 3, dtype=torch.float32)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.tensor([ x for x in range(0, 20) if x % 2 == 0])
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [7]:
x = x.new_ones(x.size(), dtype=torch.double)
print(x)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [8]:
y = torch.rand(x.size())
print(f'x+y = {x+y}')
print(f'x-y = {x-y}')
print(f'x*y = {x*y}')
print(f'x/y = {x/y}')
print()
print()
print(f'+ = {torch.add(x, y)}\n- = {torch.sub(x, y)}\n* = {torch.mul(x, y)}\n / = {torch.div(x, y)}')

x+y = tensor([1.0303, 1.8235, 1.5896, 1.5283, 1.1601, 1.3832, 1.5225, 1.8366, 1.9050,
        1.3865], dtype=torch.float64)
x-y = tensor([0.9697, 0.1765, 0.4104, 0.4717, 0.8399, 0.6168, 0.4775, 0.1634, 0.0950,
        0.6135], dtype=torch.float64)
x*y = tensor([0.0303, 0.8235, 0.5896, 0.5283, 0.1601, 0.3832, 0.5225, 0.8366, 0.9050,
        0.3865], dtype=torch.float64)
x/y = tensor([33.0262,  1.2143,  1.6961,  1.8927,  6.2472,  2.6097,  1.9137,  1.1953,
         1.1050,  2.5872], dtype=torch.float64)


+ = tensor([1.0303, 1.8235, 1.5896, 1.5283, 1.1601, 1.3832, 1.5225, 1.8366, 1.9050,
        1.3865], dtype=torch.float64)
- = tensor([0.9697, 0.1765, 0.4104, 0.4717, 0.8399, 0.6168, 0.4775, 0.1634, 0.0950,
        0.6135], dtype=torch.float64)
* = tensor([0.0303, 0.8235, 0.5896, 0.5283, 0.1601, 0.3832, 0.5225, 0.8366, 0.9050,
        0.3865], dtype=torch.float64)
 / = tensor([33.0262,  1.2143,  1.6961,  1.8927,  6.2472,  2.6097,  1.9137,  1.1953,
         1.1050,  2.5872], dtype=torch.fl

In [9]:
print(f'y+x={y.add_(x)}\ny-x={y.sub_(x)}\ny*x={y.mul_(x)}\ny/x={y.div_(x)}')

y+x=tensor([1.0303, 1.8235, 1.5896, 1.5283, 1.1601, 1.3832, 1.5225, 1.8366, 1.9050,
        1.3865])
y-x=tensor([0.0303, 0.8235, 0.5896, 0.5283, 0.1601, 0.3832, 0.5225, 0.8366, 0.9050,
        0.3865])
y*x=tensor([0.0303, 0.8235, 0.5896, 0.5283, 0.1601, 0.3832, 0.5225, 0.8366, 0.9050,
        0.3865])
y/x=tensor([0.0303, 0.8235, 0.5896, 0.5283, 0.1601, 0.3832, 0.5225, 0.8366, 0.9050,
        0.3865])


In [10]:
print(x[1:])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [11]:
x = x.new_ones(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
b = x.numpy()
print(b)
x.add_(10)
print(x)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]], dtype=torch.float64)
[[11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]]


In [13]:
import numpy as np
a = np.zeros(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [14]:
if torch.cuda.is_available():
    device = torch.device("cuda")         
    y = torch.ones_like(x, device=device) 
    x = x.to(device)                       
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], device='cuda:0', dtype=torch.float64)
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], dtype=torch.float64)
